/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trial_GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;
import javax.swing.JOptionPane;
import javax.swing.Timer;


public class Funds_Transfer extends javax.swing.JFrame {

    String card_number,acc_no,current_date;
    Timer time;
    int min=1,sec=59;
    double transfer_amount;
    double current_balance;
    String account_number;
    double beneficiary_balance;
    double updated_balance1;
    double updated_bal;
    String test_account;
    String beneficiary_card_number;
    String current_time;
    
    public Funds_Transfer() {
        initComponents();
    }
    public Funds_Transfer(String card_number,String acc_no)
    {
        this.card_number=card_number;
        this.acc_no=acc_no;
        initComponents();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        java.util.Date d = new java.util.Date();
        current_date=sdf.format(d);
        System.out.println(current_date);
       
        Calendar cal = Calendar.getInstance();
        Date date = cal.getTime();
        DateFormat dateformat = new SimpleDateFormat("HH:mm:ss");
        current_time = dateformat.format(date);
        System.out.println(current_time);
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println("Driver Loaded");
            
            //STEP 2:
            Connection conn=DriverManager.getConnection
                    ("jdbc:mysql://localhost"
                    + ":3306/ATM","root","Lavesh@2002");
            System.out.println("Connection Established");
            
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery
                     ("select account_holder,balance from login where "
                    + "card_number = '"+card_number+"'");
            
            while(rs.next())
            {
               jLabel5.setVisible(true);
               jLabel5.setText("Welcome "+rs.getString("account_holder"));
               current_balance = rs.getDouble("balance");
            }
            conn.close();
        }
        catch(ClassNotFoundException c)
        {
            System.out.println("Driver not Loaded");
        }//end of catch
        catch(SQLException s)
        {
            System.out.println("Connection not established");
        }//end of catch
        time = new Timer (1000, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e) {
            jLabel6.setText(String.valueOf(min)+" : "+String.valueOf(sec));
                  
            if(sec==0)
            {
                min--;
                sec=60;
                if(min==-1)
                {
                    time.stop(); 
                    JOptionPane.showMessageDialog(null,"Session Timed Out, Please login again");
                    Welcome w = new Welcome();
                    w.setVisible(true);
                    dispose();
                }
            }
            sec--;
        }
    });
        time.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funds Transfer - TERNA ATM");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Funds Transfer");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 132, 550, 10));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Enter Beneficiary Account Number       :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 400, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Re-Enter Beneficiary Account Number :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 410, -1));

        jTextField1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 180, 30));

        jTextField2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 180, 30));

        jButton1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Transfer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 120, 40));

        jButton2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("Back to Main Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 230, 40));

        jButton3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 102));
        jButton3.setText("Logout and Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 220, 40));

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, 30));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 100, 40));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Enter Amount to Transfer :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 290, -1));

        jTextField3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trial_GUI/abstract-white-gray-gradient-color-curve-background_48946-64.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 627, 448));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jTextField1.getText().equals("") || jTextField2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please enter "
                    + "Account Number to Proceed");
        }//end of if
        else if(jTextField3.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please enter Amount to Transfer");
        }//end of else if
        else if(!(jTextField1.getText().equals(jTextField2.getText())))
        {
            JOptionPane.showMessageDialog(this,"Please "
                    + "Re-Enter same Account Number");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
        }
        else
        {
            transfer_amount = Double.parseDouble(jTextField3.getText());
            account_number = jTextField2.getText();
            
            try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                System.out.println("Driver Loaded");
            
                //STEP 2:
                Connection conn=DriverManager.getConnection
                    ("jdbc:mysql://localhost"
                    + ":3306/ATM","root","Lavesh@2002");
                System.out.println("Connection Established");
            
                Statement st=conn.createStatement();
                ResultSet rs=st.executeQuery
                     ("select account_number from login where "
                    + "card_number = '"+card_number+"'");
            
                while(rs.next())
                {
                    test_account=rs.getString("account_number");
                }
                
                conn.close();
            }
            catch(ClassNotFoundException c)
            {
                System.out.println("Driver not Loaded");
            }//end of catch
            catch(SQLException s)
            {
                System.out.println("Connection not established");
            }//end of catch
            
            if(account_number.equals(test_account))
            {
                JOptionPane.showMessageDialog(this,"Please enter Beneficiary's Account Number");
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
            }//end of if
            else{
//Write the code here 
            try
            {
                //STEP 1:
                Class.forName("com.mysql.cj.jdbc.Driver");
                System.out.println("Driver Loaded");
            
                //STEP 2:
                Connection con=DriverManager.getConnection
                        ("jdbc:mysql://localhost"
                       + ":3306/ATM","root","Lavesh@2002");
                System.out.println("Connection Established");
            
                String sqll="select * from login where account_number=?";
                
                //STEP 3:
                PreparedStatement pstt=con.prepareStatement(sqll);
                pstt.setString(1,account_number);
                    
                //STEP 4:
                ResultSet rss= pstt.executeQuery();
                if(!(rss.next()))
                {
                    JOptionPane.showMessageDialog(this,"Beneficiary Account Not Found");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                }//end of if
                else
                {
                    if(current_balance<transfer_amount)
                    {
                        JOptionPane.showMessageDialog(this,"Insufficient Funds,"
                        + " Please try with lesser amount");
                        jTextField1.setText("");
                        jTextField2.setText("");
                        jTextField3.setText("");
                    }//end of if
                    else
                    {
                        try
                        {
                            Class.forName("com.mysql.cj.jdbc.Driver");
                            System.out.println("Driver Loaded");
            
                            //STEP 2:
                            Connection conn=DriverManager.getConnection
                            ("jdbc:mysql://localhost"
                                + ":3306/ATM","root","Lavesh@2002");
                            System.out.println("Connection Established");
            
                            updated_bal = current_balance - transfer_amount;
            
                            String command = "update login set "
                               + "balance = "+updated_bal+" WHERE card_number"
                                    + " = '"+card_number+"'";
                
                            PreparedStatement ps = conn.prepareStatement(command);
            
                            //ps.executeQuery();
                            ps.executeUpdate();
   //----------------------------------------------------------------------------             
                            Statement st=conn.createStatement();
                            ResultSet rs=st.executeQuery
                            ("select balance,card_number from login where "
                                + "account_number = "+account_number);
                            System.out.println(account_number);
                            while(rs.next())
                            {
                                beneficiary_balance = rs.getDouble("balance");
                                beneficiary_card_number=rs.getString("card_number");
                            }//end of while
           
                            updated_balance1 = beneficiary_balance + transfer_amount;
                            System.out.println(updated_balance1);
             
                            String command1 = "update login set "
                            + "balance = "+updated_balance1+" WHERE accoun"
                                    + "t_number = "+account_number;

                            PreparedStatement ps1 = conn.prepareStatement(command1);
            
                            //ps.executeQuery();
                            ps1.executeUpdate();
            
                            JOptionPane.showMessageDialog(this,"Transaction Completed, Funds Transfered!");
                            time.stop();
    //--------------------------------------------------------------------------
                            PreparedStatement stmt = conn.prepareStatement
                            ("insert into mini_statement values(?,?,?,?,?,?)");

                            stmt.setString(1,current_date);
                            stmt.setString(2,"DEBIT");
                            stmt.setString(3,card_number);
                            stmt.setString(4,acc_no);
                            stmt.setDouble(5,transfer_amount);
                            stmt.setString(6,current_time);
                            int i = stmt.executeUpdate();
  //------------------------------------------------------------------------------              
                            PreparedStatement stmt1 = conn.prepareStatement
                            ("insert into mini_statement values(?,?,?,?,?,?)");

                            stmt1.setString(1,current_date);
                            stmt1.setString(2,"CREDIT");
                            stmt1.setString(3,beneficiary_card_number);
                            stmt1.setString(4,account_number);
                            stmt1.setDouble(5,transfer_amount);
                            stmt1.setString(6,current_time);

                            int j = stmt1.executeUpdate();

                            Main_Menu m = new Main_Menu(card_number);
                            m.setVisible(true);
                            dispose();
                
                            conn.close();       
                        }//end of try          
                        catch(ClassNotFoundException c)
                        {
                            System.out.println("Driver not Loaded");
                        }//end of catch
                        catch(SQLException s)
                        {
                            System.out.println("Connection not established");
                        }//end of catch
                    }//end of inner else
                }//end of inner else
                //STEP 5:
                con.close();
            }//end of try
            catch(ClassNotFoundException c)
            {
                System.out.println("Driver not Loaded");
            }//end of catch
            catch(SQLException s)
            {
                System.out.println("Connection not established");
            }//end of catch
        
        }//end of else
      }//end of else
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        time.stop();
        Main_Menu m = new Main_Menu(card_number);
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        int length = (jTextField1.getText()).length();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(length<15)
            {
                jTextField1.setEditable(true);
            }
            else
            {
                jTextField1.setEditable(false);
            }
        }//end of if
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||
                    evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                jTextField1.setEditable(true);
            }
            else
            {
                jTextField1.setEditable(false);
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        int length = (jTextField2.getText()).length();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(length<15)
            {
                jTextField2.setEditable(true);
            }
            else
            {
                jTextField2.setEditable(false);
            }
        }//end of if
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||
                    evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                jTextField2.setEditable(true);
            }
            else
            {
                jTextField2.setEditable(false);
            }
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        int length = (jTextField3.getText()).length();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(length<7)
            {
                jTextField3.setEditable(true);
            }
            else
            {
                jTextField3.setEditable(false);
            }
        }//end of if
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||
                    evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                jTextField3.setEditable(true);
            }
            else
            {
                jTextField3.setEditable(false);
            }
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Do you really want to exit?", "Confirm", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_NO_OPTION)
        {
            time.stop();
            Welcome w=new Welcome();
            w.setVisible(true);
            dispose();
        }  
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funds_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funds_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funds_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funds_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funds_Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
